c       ************************ PROGRAM SS_input_gen.f ****************************
c          Reads input file exported from CAST, replaces recharge BC with RET SS
c          input, and replaces Output Control card.
c
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
c
      CHARACTER infile1*80,infile2*80,infile3*80,outfile1*80
      CHARACTER line1*1024,frmt*10,bcn*10
      CHARACTER date*8,time*10
c
      CALL DATE_AND_TIME (date,time)
c
      infile1="../build/input"
      infile2="../ret/ca_ss_boundary_card.dat"
      infile3="SS_Output_Control.dat"
      outfile1="input_SS"
c
      OPEN(20,FILE=outfile1,
     >  STATUS='REPLACE',IOSTAT=IST)
c
      WRITE(20,"(2a)") '# Steady-state input file generated by ',
     >  'SS_input_gen_olive.exe  Version 1.0 - 11-8-2019'
      WRITE(20,"(12a)") '# Run on ',date(5:6),'-',
     >  date(7:8),'-',date(1:4),' at ',time(1:2),':',
     >  time(3:4),':',time(5:6)
      WRITE(20,"(a)") '#'
c
      OPEN(11,FILE=infile1,STATUS='OLD'
     >  ,IOSTAT=IST)
c
   50 READ(11,"(a1024)",END=9989) line1
      DO ii=1,1024
        IF(line1(ii:ii+29).eq.'~Solute/Fluid Interaction Card') GOTO 60
      ENDDO
      llen=len(trim(line1))
      IF(llen.eq.0) THEN
        WRITE(20,"(a)")
      Else
        WRITE(frmt,"(i5)") llen
        WRITE(20,"(a"//frmt//")") line1
      ENDIF
      GOTO 50
c
   60 READ(11,"(a1024)",END=9990) line1
      DO ii=1,1024
        IF(line1(ii:ii+23).eq.'~Initial Conditions Card') GOTO 70
      ENDDO
      GOTO 60
c
   70 llen=len(trim(line1))
      WRITE(frmt,"(i5)") llen
      WRITE(20,"(a"//frmt//")") line1
c
  100 READ(11,"(a1024)",END=9991) line1
      DO ii=1,1024
        IF(line1(ii:ii+24).eq.'~Boundary Conditions Card') GOTO 200
      ENDDO
      llen=len(trim(line1))
      IF(llen.eq.0) THEN
        WRITE(20,"(a)")
      Else
        WRITE(frmt,"(i5)") llen
        WRITE(20,"(a"//frmt//")") line1
      ENDIF
      GOTO 100
c
  200 OPEN(12,FILE=infile2,STATUS='OLD'
     >  ,IOSTAT=IST)
      llen=len(trim(line1))
      WRITE(frmt,"(i5)") llen
      WRITE(20,"(a"//frmt//")") line1
      WRITE(20,"(2a)") '#------------------------',
     >  '------------------------------------------'
  210 READ(12,"(a1024)",END=9992) line1
      IF(line1(1:1).ne.'#') GOTO 220
      llen=len(trim(line1))
      IF(llen.eq.0) THEN
        WRITE(20,"(a)")
      Else
        WRITE(frmt,"(i5)") llen
        WRITE(20,"(a"//frmt//")") line1
      ENDIF
      GOTO 210
c
  220 READ(line1,*) nbc
      WRITE(bcn,"(i5)") nbc+1
      llen=len(trim(ADJUSTL(bcn)))
      WRITE(frmt,"(i5)") llen
      WRITE(20,"(a"//frmt//",a1)") ADJUSTL(bcn),','
  230 READ(12,"(a1024)",END=300) line1
      llen=len(trim(line1))
      IF(llen.eq.0) THEN
        WRITE(20,"(a)")
      Else
        WRITE(frmt,"(i5)") llen
        WRITE(20,"(a"//frmt//")") line1
      ENDIF
      GOTO 230
c
  300 WRITE(20,"(a)") 'file, input.bot, Dirichlet Aqueous,'
      WRITE(20,"(a)") '1,'
      WRITE(20,"(a)") '0, year, 101325, Pa,'
      WRITE(20,"(2a)") '#---------------------------------------',
     >  '---------------------------'
      WRITE(20,"(a)")
      WRITE(20,"(2a)") '#---------------------------------------',
     >  '---------------------------'
c
  310 READ(11,"(a1024)",END=9993) line1
      DO ii=1,1024
        IF(line1(ii:ii+11).eq.'~Source Card') GOTO 400
      ENDDO
      GOTO 310
c
  400 llen=len(trim(line1))
      WRITE(frmt,"(i5)") llen
      WRITE(20,"(a"//frmt//")") line1
  410 READ(11,"(a1024)",END=9993) line1
      DO ii=1,1024
        IF(line1(ii:ii+19).eq.'~Output Control Card') GOTO 500
      ENDDO
      llen=len(trim(line1))
      IF(llen.eq.0) THEN
        WRITE(20,"(a)")
      Else
        WRITE(frmt,"(i5)") llen
        WRITE(20,"(a"//frmt//")") line1
      ENDIF
      GOTO 410
c
  500 OPEN(13,FILE=infile3,STATUS='OLD'
     >  ,IOSTAT=IST)
      READ(13,"(a1024)") line1
  510 READ(13,"(a1024)",END=600) line1
      llen=len(trim(line1))
      IF(llen.eq.0) THEN
        WRITE(20,"(a)")
      Else
        WRITE(frmt,"(i5)") llen
        WRITE(20,"(a"//frmt//")") line1
      ENDIF
      GOTO 510
c
  600 WRITE(20,"(a)")
      llen=len(trim(line1))
      IF(llen.eq.0) THEN
        WRITE(20,"(a)")
      Else
        WRITE(frmt,"(i5)") llen
        WRITE(20,"(a"//frmt//")") line1
      ENDIF
  610 READ(11,"(a1024)",END=9994) line1
      DO ii=1,1024
        IF(line1(ii:ii+17).eq.'~Surface Flux Card') GOTO 700
      ENDDO
      GOTO 610
c
  700 llen=len(trim(line1))
      IF(llen.eq.0) THEN
        WRITE(20,"(a)")
      Else
        WRITE(frmt,"(i5)") llen
        WRITE(20,"(a"//frmt//")") line1
      ENDIF
  710 READ(11,"(a1024)",END=9999) line1
      llen=len(trim(line1))
      IF(llen.eq.0) THEN
        WRITE(20,"(a)")
      Else
        WRITE(frmt,"(i5)") llen
        WRITE(20,"(a"//frmt//")") line1
      ENDIF
      GOTO 710
c
      GOTO 9999
c
 9989 WRITE(*,*) ' Solute/Fluid Interaction Card not found'
      GOTO 9999
c
 9990 WRITE(*,*) ' Initial Conditions Card not found'
      GOTO 9999
c
 9991 WRITE(*,*) ' Boundary Conditions Card not found'
      GOTO 9999
c
 9992 WRITE(*,*) ' RET input all comments'
      GOTO 9999
c
 9993 WRITE(*,*) ' Bottom not found'
      GOTO 9999
c
 9994 WRITE(*,*) ' Surface Flux Card not ended'
      GOTO 9999
c
 9995 WRITE(*,*) ' Did not find node'
      GOTO 9999
c
 9996 WRITE(*,*) ' Reference Node Variables not found'
      GOTO 9999
c
 9997 WRITE(*,*) ' Reference Node Variables not ended'
      GOTO 9999
c
 9999 CONTINUE
      STOP
      END
